feat: Add utility function to retrieve function credentials
crossplane-contrib/function-go-templating pull request #151
Opened 2024-12-27 19:10 UTC by mcfarlanem

### Description of your changes

This PR creates a new utility function getCredentialData facilitating the retrieval of function credentials so they can be used when composing Crossplane resource in Go Templates. 

Fixes #74 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Added or updated unit tests for my change.

[contribution process]: https://git.io/fj2m9
[docs]: https://docs.crossplane.io/contribute/contribute

2025-03-18 14:11 UTC, undefinedhuman commented
Hey there, any updates on this?

2025-08-21 19:48 UTC, bobh66 requested changes
Thanks @mcfarlanem - a couple of small changes, otherwise LGTM.

2025-08-21 19:48 UTC, bobh66 commented on example/functions/getCredentialData/README.md
> +You can run your function locally and test it with [`crossplane render`](https://docs.crossplane.io/v1.18/cli/command-reference/#render/)
```suggestion
You can run your function locally and test it with [`crossplane render`](https://docs.crossplane.io/latest/cli/command-reference/#render/)
```

2025-08-21 19:48 UTC, bobh66 commented on example/functions/getCredentialData/functions.yaml
> +  package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.8.0
```suggestion
  package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.810.0
```

2025-08-21 19:48 UTC, bobh66 commented on function_maps.go
> +		data = req.GetCredentials()[credName].GetCredentialData().GetData()
Can this just return here?

2025-08-21 22:32 UTC, bobh66 commented on example/functions/getCredentialData/functions.yaml
> +  package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.810.0
```suggestion
  package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.10.0
```
Apologies if the error was in my suggested changes.

2025-08-21 22:34 UTC, bobh66 commented
@mcfarlanem  - also commits need to be signed off for DCO to pass

2025-08-21 22:38 UTC, mcfarlanem commented on example/functions/getCredentialData/functions.yaml
> +  package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.810.0
All good!

2025-08-26 00:23 UTC, mcfarlanem commented
@bobh66 rebase complete.  Thanks.

2025-08-26 17:51 UTC, merged